# Generated by Django 5.1.7 on 2025-03-22 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('lat', models.FloatField()),
                ('long', models.FloatField()),
                ('distance', models.FloatField(help_text='Trail distance in miles')),
                ('elevation', models.FloatField(help_text='Elevation gain in feet')),
                ('difficulty', models.CharField(choices=[('Easy', 'Easy'), ('Moderate', 'Moderate'), ('Hard', 'Hard')], max_length=50)),
                ('is_dog_friendly', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TrailImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='trail_images/')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('trail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='trail_nav.trail')),
            ],
        ),
    ]
