# Generated by Django 5.1.7 on 2025-03-26 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trail_nav', '0002_navigationsession_gpslog'),
    ]

    operations = [
        migrations.AddField(
            model_name='trail',
            name='is_hiking_trail',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='trail',
            name='difficulty',
            field=models.CharField(default='Moderate', max_length=50),
        ),
        migrations.AlterField(
            model_name='trail',
            name='distance',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='trail',
            name='elevation',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='trailimage',
            name='image',
            field=models.URLField(),
        ),
    ]
